#!/bin/bash

# Quick Reference: Running Training with Adaptive Entropy Scheduling

echo "=========================================="
echo "Adaptive Entropy Scheduling - Quick Start"
echo "=========================================="
echo ""

echo "1. STANDARD (Recommended for most cases)"
echo "   Start: 0.01, End: 0.001, Decay: 10k episodes"
echo ""
echo "python main_a2c.py \\"
echo "    --city nyc_manhattan \\"
echo "    --mode 2 \\"
echo "    --max_episodes 15000 \\"
echo "    --entropy_coef_start 0.01 \\"
echo "    --entropy_coef_end 0.001 \\"
echo "    --entropy_decay_episodes 10000 \\"
echo "    --checkpoint_path standard_entropy"
echo ""

echo "2. HIGH EXPLORATION (For complex/noisy environments)"
echo "   Start: 0.02, End: 0.005, Decay: 12k episodes"
echo ""
echo "python main_a2c.py \\"
echo "    --city nyc_manhattan \\"
echo "    --mode 2 \\"
echo "    --max_episodes 15000 \\"
echo "    --entropy_coef_start 0.02 \\"
echo "    --entropy_coef_end 0.005 \\"
echo "    --entropy_decay_episodes 12000 \\"
echo "    --checkpoint_path high_exploration"
echo ""

echo "3. FAST CONVERGENCE (When you need quick results)"
echo "   Start: 0.005, End: 0.0001, Decay: 7k episodes"
echo ""
echo "python main_a2c.py \\"
echo "    --city nyc_manhattan \\"
echo "    --mode 2 \\"
echo "    --max_episodes 15000 \\"
echo "    --entropy_coef_start 0.005 \\"
echo "    --entropy_coef_end 0.0001 \\"
echo "    --entropy_decay_episodes 7000 \\"
echo "    --checkpoint_path fast_convergence"
echo ""

echo "4. NO DECAY (Fixed entropy for debugging)"
echo "   Start: 0.01, End: 0.01, Decay: 0 (disabled)"
echo ""
echo "python main_a2c.py \\"
echo "    --city nyc_manhattan \\"
echo "    --mode 2 \\"
echo "    --max_episodes 15000 \\"
echo "    --entropy_coef_start 0.01 \\"
echo "    --entropy_coef_end 0.01 \\"
echo "    --entropy_decay_episodes 0 \\"
echo "    --checkpoint_path fixed_entropy"
echo ""

echo "=========================================="
echo "Monitoring in Weights & Biases"
echo "=========================================="
echo ""
echo "Key metrics to watch:"
echo "  1. entropy/coef              - Should linearly decrease"
echo "  2. entropy/mean              - Should gradually drop from ~0.7 to ~0.2"
echo "  3. signal/entropy_to_pg_ratio - Target: 0.10-0.30 (mid-training)"
echo "  4. signal/policy_gradient_mean - Main learning signal"
echo "  5. signal/entropy_term_mean    - Exploration signal"
echo ""
echo "Tuning guide:"
echo "  - If ratio > 0.40: Decrease entropy_coef_start"
echo "  - If ratio < 0.10: Increase entropy_coef_start"
echo "  - If convergence too fast: Increase entropy_decay_episodes"
echo "  - If convergence too slow: Decrease entropy_decay_episodes"
echo ""

echo "=========================================="
echo "Example: Full Training Command"
echo "=========================================="
echo ""
echo "python main_a2c.py \\"
echo "    --seed 42 \\"
echo "    --city nyc_manhattan \\"
echo "    --mode 2 \\"
echo "    --max_episodes 15000 \\"
echo "    --hidden_size 256 \\"
echo "    --p_lr 1e-4 \\"
echo "    --q_lr 1e-3 \\"
echo "    --actor_clip 5.0 \\"
echo "    --critic_clip 5.0 \\"
echo "    --gamma 0.97 \\"
echo "    --reward_scale 0.00005 \\"
echo "    --advantage_clip 10.0 \\"
echo "    --entropy_coef_start 0.01 \\"
echo "    --entropy_coef_end 0.001 \\"
echo "    --entropy_decay_episodes 10000 \\"
echo "    --checkpoint_path my_training_run"
echo ""
