_wandb:
    value:
        cli_version: 0.22.0
        e:
            yclgj08u0ko4e24cxo99d0zgw9vqe2qo:
                args:
                    - --mode
                    - "2"
                    - --max_episodes
                    - "100"
                    - --checkpoint_path
                    - mode2_dual_agent_test
                    - --city
                    - san_francisco
                codePath: main_a2c_multi_agent.py
                codePathLocal: main_a2c_multi_agent.py
                cpu_count: 16
                cpu_count_logical: 16
                disk:
                    /:
                        total: "76817485824"
                        used: "8543866880"
                email: emilkraghtoft@gmail.com
                executable: /zhome/7a/c/204061/Documents/thesis/rl-pricing-amod/thesis_env/bin/python
                git:
                    commit: cb3ee3fdfa2ce69379cfca81dfc52455672d57c8
                    remote: https://github.com/emto17ab/rl-pricing-amod.git
                host: hpclogin1
                memory:
                    total: "810200051712"
                os: Linux-6.1.149-1.el9.elrepo.x86_64-x86_64-with-glibc2.34
                program: /work3/s233791/rl-pricing-amod/main_a2c_multi_agent.py
                python: CPython 3.10.18
                root: /work3/s233791/rl-pricing-amod
                startedAt: "2025-10-07T12:22:20.821775Z"
                writerId: yclgj08u0ko4e24cxo99d0zgw9vqe2qo
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 16
            "4": 3.10.18
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
batch_size:
    value: 100
beta:
    value: 0.5
checkpoint_path:
    value: mode2_dual_agent_test
choice_price_mult:
    value: 1
city:
    value: san_francisco
clip:
    value: 500
cplexpath:
    value: /apps/cplex/cplex1210/opl/bin/x86-64_linux/
cuda:
    value: false
demand_ratio:
    value: 1
directory:
    value: saved_files
gamma:
    value: 0.97
hidden_size:
    value: 256
impute:
    value: 0
jitter:
    value: 1
json_hr:
    value: 7
json_tstep:
    value: 3
load:
    value: false
look_ahead:
    value: 6
max_episodes:
    value: 100
max_steps:
    value: 20
maxt:
    value: 2
mode:
    value: 2
p_lr:
    value: 0.001
q_lr:
    value: 0.001
scale_factor:
    value: 0.01
seed:
    value: 10
supply_ratio:
    value: 1
test:
    value: false
